function CodeDefine() { 
this.def = new Array();
this.def["IsrOverrun"] = {file: "ert_main_c.html",line:27,type:"var"};
this.def["OverrunFlag"] = {file: "ert_main_c.html",line:28,type:"var"};
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:29,type:"fcn"};
this.def["main"] = {file: "ert_main_c.html",line:47,type:"fcn"};
this.def["TestMPU6050_B"] = {file: "TestMPU6050_c.html",line:25,type:"var"};
this.def["TestMPU6050_DW"] = {file: "TestMPU6050_c.html",line:28,type:"var"};
this.def["TestMPU6050_M_"] = {file: "TestMPU6050_c.html",line:31,type:"var"};
this.def["TestMPU6050_M"] = {file: "TestMPU6050_c.html",line:32,type:"var"};
this.def["TestMPU6050_step"] = {file: "TestMPU6050_c.html",line:35,type:"fcn"};
this.def["TestMPU6050_initialize"] = {file: "TestMPU6050_c.html",line:94,type:"fcn"};
this.def["TestMPU6050_terminate"] = {file: "TestMPU6050_c.html",line:163,type:"fcn"};
this.def["B_TestMPU6050_T"] = {file: "TestMPU6050_h.html",line:85,type:"type"};
this.def["DW_TestMPU6050_T"] = {file: "TestMPU6050_h.html",line:93,type:"type"};
this.def["P_TestMPU6050_T"] = {file: "TestMPU6050_types_h.html",line:26,type:"type"};
this.def["RT_MODEL_TestMPU6050_T"] = {file: "TestMPU6050_types_h.html",line:29,type:"type"};
this.def["TestMPU6050_P"] = {file: "TestMPU6050_data_c.html",line:24,type:"var"};
this.def["chunk_T"] = {file: "multiword_types_h.html",line:27,type:"type"};
this.def["uchunk_T"] = {file: "multiword_types_h.html",line:28,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:82,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:87,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:92,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:99,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:106,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:113,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:120,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:127,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:134,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:152,type:"type"};
this.def["rtDataTypeSizes"] = {file: "TestMPU6050_dt_h.html",line:23,type:"var"};
this.def["rtDataTypeNames"] = {file: "TestMPU6050_dt_h.html",line:41,type:"var"};
this.def["rtBTransitions"] = {file: "TestMPU6050_dt_h.html",line:59,type:"var"};
this.def["rtBTransTable"] = {file: "TestMPU6050_dt_h.html",line:69,type:"var"};
this.def["rtPTransitions"] = {file: "TestMPU6050_dt_h.html",line:75,type:"var"};
this.def["rtPTransTable"] = {file: "TestMPU6050_dt_h.html",line:82,type:"var"};
this.def["initMPU6050"] = {file: "MPU6050_c.html",line:18,type:"fcn"};
this.def["readMPU6050_XAcceleration"] = {file: "MPU6050_c.html",line:25,type:"fcn"};
this.def["readMPU6050_YAcceleration"] = {file: "MPU6050_c.html",line:37,type:"fcn"};
this.def["readMPU6050_ZAcceleration"] = {file: "MPU6050_c.html",line:49,type:"fcn"};
this.def["readMPU6050_XGyroscope"] = {file: "MPU6050_c.html",line:61,type:"fcn"};
this.def["readMPU6050_YGyroscope"] = {file: "MPU6050_c.html",line:73,type:"fcn"};
this.def["readMPU6050_ZGyroscope"] = {file: "MPU6050_c.html",line:85,type:"fcn"};
this.def["readByte"] = {file: "MPU6050_c.html",line:97,type:"fcn"};
this.def["writeByte"] = {file: "MPU6050_c.html",line:112,type:"fcn"};
this.def["startTransmission"] = {file: "MPU6050_c.html",line:128,type:"fcn"};
this.def["initI2CPins"] = {file: "MPU6050_c.html",line:151,type:"fcn"};
this.def["initI2C"] = {file: "MPU6050_c.html",line:167,type:"fcn"};
this.def["I2C_DeInit"] = {file: "stm32f4xx_i2c_c.html",line:132,type:"fcn"};
this.def["I2C_Init"] = {file: "stm32f4xx_i2c_c.html",line:175,type:"fcn"};
this.def["I2C_StructInit"] = {file: "stm32f4xx_i2c_c.html",line:284,type:"fcn"};
this.def["I2C_Cmd"] = {file: "stm32f4xx_i2c_c.html",line:308,type:"fcn"};
this.def["I2C_GenerateSTART"] = {file: "stm32f4xx_i2c_c.html",line:332,type:"fcn"};
this.def["I2C_GenerateSTOP"] = {file: "stm32f4xx_i2c_c.html",line:356,type:"fcn"};
this.def["I2C_Send7bitAddress"] = {file: "stm32f4xx_i2c_c.html",line:384,type:"fcn"};
this.def["I2C_AcknowledgeConfig"] = {file: "stm32f4xx_i2c_c.html",line:411,type:"fcn"};
this.def["I2C_OwnAddress2Config"] = {file: "stm32f4xx_i2c_c.html",line:434,type:"fcn"};
this.def["I2C_DualAddressCmd"] = {file: "stm32f4xx_i2c_c.html",line:461,type:"fcn"};
this.def["I2C_GeneralCallCmd"] = {file: "stm32f4xx_i2c_c.html",line:485,type:"fcn"};
this.def["I2C_SoftwareResetCmd"] = {file: "stm32f4xx_i2c_c.html",line:511,type:"fcn"};
this.def["I2C_StretchClockCmd"] = {file: "stm32f4xx_i2c_c.html",line:535,type:"fcn"};
this.def["I2C_FastModeDutyCycleConfig"] = {file: "stm32f4xx_i2c_c.html",line:561,type:"fcn"};
this.def["I2C_NACKPositionConfig"] = {file: "stm32f4xx_i2c_c.html",line:599,type:"fcn"};
this.def["I2C_SMBusAlertConfig"] = {file: "stm32f4xx_i2c_c.html",line:627,type:"fcn"};
this.def["I2C_ARPCmd"] = {file: "stm32f4xx_i2c_c.html",line:651,type:"fcn"};
this.def["I2C_SendData"] = {file: "stm32f4xx_i2c_c.html",line:689,type:"fcn"};
this.def["I2C_ReceiveData"] = {file: "stm32f4xx_i2c_c.html",line:702,type:"fcn"};
this.def["I2C_TransmitPEC"] = {file: "stm32f4xx_i2c_c.html",line:733,type:"fcn"};
this.def["I2C_PECPositionConfig"] = {file: "stm32f4xx_i2c_c.html",line:764,type:"fcn"};
this.def["I2C_CalculatePEC"] = {file: "stm32f4xx_i2c_c.html",line:788,type:"fcn"};
this.def["I2C_GetPEC"] = {file: "stm32f4xx_i2c_c.html",line:810,type:"fcn"};
this.def["I2C_DMACmd"] = {file: "stm32f4xx_i2c_c.html",line:843,type:"fcn"};
this.def["I2C_DMALastTransferCmd"] = {file: "stm32f4xx_i2c_c.html",line:867,type:"fcn"};
this.def["I2C_ReadRegister"] = {file: "stm32f4xx_i2c_c.html",line:1005,type:"fcn"};
this.def["I2C_ITConfig"] = {file: "stm32f4xx_i2c_c.html",line:1032,type:"fcn"};
this.def["I2C_CheckEvent"] = {file: "stm32f4xx_i2c_c.html",line:1091,type:"fcn"};
this.def["I2C_GetLastEvent"] = {file: "stm32f4xx_i2c_c.html",line:1139,type:"fcn"};
this.def["I2C_GetFlagStatus"] = {file: "stm32f4xx_i2c_c.html",line:1194,type:"fcn"};
this.def["I2C_ClearFlag"] = {file: "stm32f4xx_i2c_c.html",line:1271,type:"fcn"};
this.def["I2C_GetITStatus"] = {file: "stm32f4xx_i2c_c.html",line:1305,type:"fcn"};
this.def["I2C_ClearITPendingBit"] = {file: "stm32f4xx_i2c_c.html",line:1365,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["TestMPU6050_c.html"] = "../TestMPU6050.c";
	this.html2Root["TestMPU6050_c.html"] = "TestMPU6050_c.html";
	this.html2SrcPath["TestMPU6050_h.html"] = "../TestMPU6050.h";
	this.html2Root["TestMPU6050_h.html"] = "TestMPU6050_h.html";
	this.html2SrcPath["TestMPU6050_private_h.html"] = "../TestMPU6050_private.h";
	this.html2Root["TestMPU6050_private_h.html"] = "TestMPU6050_private_h.html";
	this.html2SrcPath["TestMPU6050_types_h.html"] = "../TestMPU6050_types.h";
	this.html2Root["TestMPU6050_types_h.html"] = "TestMPU6050_types_h.html";
	this.html2SrcPath["TestMPU6050_data_c.html"] = "../TestMPU6050_data.c";
	this.html2Root["TestMPU6050_data_c.html"] = "TestMPU6050_data_c.html";
	this.html2SrcPath["multiword_types_h.html"] = "../multiword_types.h";
	this.html2Root["multiword_types_h.html"] = "multiword_types_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["TestMPU6050_dt_h.html"] = "../TestMPU6050_dt.h";
	this.html2Root["TestMPU6050_dt_h.html"] = "TestMPU6050_dt_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MPU6050_c.html"] = "../../MPU6050/source/MPU6050.c";
	this.html2Root["MPU6050_c.html"] = "MPU6050_c.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["stm32f4xx_i2c_c.html"] = "../../MPU6050/source/stm32f4xx_i2c.c";
	this.html2Root["stm32f4xx_i2c_c.html"] = "stm32f4xx_i2c_c.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","TestMPU6050_c.html","TestMPU6050_h.html","TestMPU6050_private_h.html","TestMPU6050_types_h.html","TestMPU6050_data_c.html","multiword_types_h.html","rtwtypes_h.html","TestMPU6050_dt_h.html","rtmodel_h.html","MPU6050_c.html","MW_target_hardware_resources_h.html","stm32f4xx_i2c_c.html"];
